
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="LGPLv3"

[[mods]] #mandatory

modId="template_mod" #mandatory

version = "${version}"

displayName="Template Mod" #mandatory

logoFile="icon.png" #optional

credits="Ordana" #optional

authors="Ordana" #optional

itemIcon="template_mod:template" #catalogue icon
description='''
Template Mod Description
'''

[[dependencies.template_mod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[40,)" #mandatory

    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.template_mod]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.template_mod]]

    modId="moonlight"
    mandatory=true
    versionRange="[1.19.2-2.0.35,]"
    ordering="AFTER"
    side="BOTH"
