
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="LGPLv3"

[[mods]] #mandatory

modId="dont_drop_your_compass" #mandatory

version = "${version}"

displayName="Dont Drop Your Compass" #mandatory

logoFile="icon.png" #optional

credits="Ordana" #optional

authors="Ordana" #optional

itemIcon="dont_drop_your_compass:template" #catalogue icon
description='''
Recall Compasses no longer drop upon death!
'''

[[dependencies.dont_drop_your_compass]] #optional
    # the modid of the dependency
    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[40,)" #mandatory

    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.dont_drop_your_compass]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
